name:                dining-phils-cm
version:             0.1.0.0
github:              "wizardpb/dining-phils-cm"
license:             BSD3
author:              "Paul Bennett"
maintainer:          "wizardpg@gmail.com"
copyright:           "Copyright (c) 2018- Paul Bennett"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wizardpb/dining-phils-cm#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- time >= 1.9.2

library:
  source-dirs: src

executables:
  dining-phils-cm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dining-phils-cm

tests:
  dining-phils-cm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dining-phils-cm
